pipeline:
  build:
    image: node:8
    commands:
      - npm install
      - npm test
      - npm run build

  docker:
    image: docker
    commands:
      - docker ps
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  deploy_staging:
    image: alpine
    commands:
      - cp -rf build /www/staging/
    volumes:
      - /mobstaff/www/staging:/www/staging
    when:
      branch: develop
      status: success