pipeline:
  build:
    image: node:8
    commands:
      - npm install
      - npm test
      - npm run build

  deploy_staging:
    image: alpine
    commands:
      - cp -rf build /www/staging/
    volumes:
      - /mobstaff/www/staging:/www/staging
    when:
      branch: master
      status: success

  deploy_production:
    image: alpine
    commands:
      - cp -rf build /www/production/
    volumes:
      - /mobstaff/www/production:/www/production
    when:
      event: [ tag, deployment ]