pipeline:
  build:
    image: node:8
    commands:
      - npm install
      - npm test
      - npm run build

  deploy_staging:
    image: alpine
    commands:
      - cp -rf build /www/staging/
    volumes:
      - /mobstaff/www/staging:/www/staging
    when:
      branch: master
      status: success